{
 "title": "WebLogic Benefits Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Benefits Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_total_bytes{task_name=\"weblogic-benefits-app2.dept-a\"}"
    },
    {
     "expr": "mem_rss_bytes{task_name=\"weblogic-benefits-app2.dept-a\"}"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_tx_packets{task_name=\"weblogic-benefits-app2.dept-a\"}"
    },
    {
     "expr": "net_rx_packets{task_name=\"weblogic-benefits-app2.dept-a\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{task_name=\"weblogic-benefits-app2.dept-a\"}"
    },
    {
     "expr": "cpu_usage_guest{task_name=\"weblogic-benefits-app2.dept-a\"}"
    },
    {
     "expr": "cpu_usage_steal{task_name=\"weblogic-benefits-app2.dept-a\"}"
    }
   ]
  }
 ]
}